### ISSUE TITLE
Getting missing module error when running npm run serve

### ISSUE THREAD

**Issue by jamiesteven** [itsdrew/td-websocket-vue#1]
``` error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/jamie/Development/td-websocket-vue/src/main.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
```

Getting the following error on ``npm run serve``. Attempting to compile on Mac OS running Node 14.2.0.

**Comment by itsdrew** [comment]
I just cloned and followed the instructions that I wrote as a sanity check, everything seemed to work fine.

I'm on node 12.5.0. When I have some time i'll try it with the current LTS version 12.16.3. Try it with node 12 and see if it works. A quick googling seems like that same error occurs with other projects with higher versions of node.

**Comment by malcolmhartley** [comment]
Been looking everywhere for this. Thank you so much for saving me from days of trying to understand what TDAmeritrade passed off as their WebSocket documentation.
